<?php

namespace Pmf\GameInterfaceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NationalTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalTeamRepository extends EntityRepository
{
}