<?php

namespace Pmf\GameInterfaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContinentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContinentRepository extends EntityRepository
{
}